"""Offline LLM-assisted KB drafting — the "B assist" half of spec §4.3.

Drafts are written with `reviewed: false`, which load_kb() refuses. A human
reviews, edits, flips the flag, and commits. Nothing here runs at request time,
and nothing under engine/ or api/ may import this module.

    export ANTHROPIC_API_KEY=...
    python kb_tools/draft_kb.py astrology sun_signs

Writes kb/astrology/sun_signs.draft.yaml — rename it only after review.
"""

from __future__ import annotations

import sys
from pathlib import Path

import anthropic
import yaml

from engine.kb.facets import load_taxonomy
from engine.kb.manifest import load_manifest

ROOT = Path(__file__).resolve().parents[1]
MODEL = "claude-opus-5"

PROMPT = """\
You are drafting entries for a curated identity-mapping knowledge base.

Style guide:
{style_guide}

The facet taxonomy — you may ONLY use these facet ids:
{facets}

Draft one entry for each of these keys in the {system} system, element {element}:
{keys}

Return YAML only, no prose, in exactly this shape:

entries:
  <key>:
    label: "<short human label>"
    text: "<one or two sentences per the style guide>"
    tags:
      - {{facet: <facet id>, weight: <0.5-0.9>, direction: high|low}}
"""


def draft(system: str, element: str) -> Path:
    manifest = load_manifest()
    keys = manifest[(system, element)]
    taxonomy = load_taxonomy()
    style_guide = (ROOT / "kb_tools" / "style_guide.md").read_text(encoding="utf-8")

    client = anthropic.Anthropic()
    message = client.messages.create(
        model=MODEL,
        max_tokens=8000,
        messages=[
            {
                "role": "user",
                "content": PROMPT.format(
                    style_guide=style_guide,
                    facets="\n".join(
                        f"- {f.id}: {f.label} (high={f.high_label}, low={f.low_label})"
                        for f in sorted(taxonomy.facets.values(), key=lambda x: x.id)
                    ),
                    system=system,
                    element=element,
                    keys="\n".join(f"- {k}" for k in keys),
                ),
            }
        ],
    )

    body = yaml.safe_load(message.content[0].text)
    document = {
        "schema": "kb.mapping.v1",
        "system": system,
        "element": element,
        # Deliberately false: an unreviewed draft must never load.
        "reviewed": False,
        "source": f"DRAFT — generated by kb_tools/draft_kb.py using {MODEL}. "
        "Replace this line with the tradition and interpretive choices "
        "you are committing to before setting reviewed: true.",
        "entries": body["entries"],
    }

    out = ROOT / "kb" / system / f"{element}.draft.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(yaml.safe_dump(document, allow_unicode=True, sort_keys=False), encoding="utf-8")
    return out


if __name__ == "__main__":
    path = draft(sys.argv[1], sys.argv[2])
    print(
        f"drafted {path}\nReview it, write a real source header, set "
        f"reviewed: true, then rename off .draft.yaml"
    )
